server:
  port: 8082

spring:
  application:
    name: stickybeak-product
  config:
    import:
      - optional:nacos:stickybeak-product.yml
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        file-extension: yml

management:
  endpoints:
    web:
      exposure:
        include: health,info
